project:
  type: book

book:
  title: "Easy NEX-GDDP-CMIP6"
  author: "Valerio Pascucci,  Luis Sanchez, Giorgio Scorzelli, Aashish Panta, and Arleth Salinas"
  date: "7/20/2024"
  cover-image: images/nasa-cover.png
  chapters:
    - index.qmd
    - intro.qmd
    - examples.qmd
    - read_different_variables.qmd
    - computer_temperature_trend.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    cover-image: images/nasa-cover.png
    theme: cosmo
    toc: true
    toc-depth: 5
  pdf:
    documentclass: scrreprt
    cover-image: images/nasa-cover.png


execute:
  echo: false
jupyter: python3
