project:
  type: book

book:
  title: "It is easy to use the NEX-GDDP-CMIP6 data!"
  author: "Aashish Panta, Valerio Pascucci,  Luis Sanchez, Giorgio Scorzelli"
  date: "09/31/2024"
  cover-image: NASA_data.png
  chapters:
    - index.qmd
    - 001_intro.qmd
    - 002_examples.qmd
    - allvars.md
    - 003_read_different_varibles.qmd
    - 004_compute_temperature_trend.qmd
    - 999_references.qmd

bibliography: references.bib

format:
  html:
    cover-image: NASA_data.png
    theme: cosmo
    toc: true
    toc-depth: 5
  pdf:
    documentclass: scrreprt
    cover-image: NASA_data.png


execute:
  echo: false
  python: /home/sci/aashishp/miniconda3/envs/cmip6/bin/python
jupyter: python3
